[package]
name = "oktaws"
version = "0.10.1"
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_str = "0.1"
toml = "0.5"
rusoto_core = "0.38"
rusoto_sts = "0.38"
rusoto_credential = "0.17"
base64 = "0.10"
structopt = "0.2"
structopt-derive = "0.2"
failure = "0.1"
snafu = "0.2"
log = "0.4"
keyring = "0.6" # 0.7 causes MacOS to constantly prompt for keyring password
username = "0.2"
dialoguer = "0.3"
sxd-document = "0.3"
sxd-xpath = "0.4"
kuchiki = "0.7"
regex = "1"
serde_ini = "0.2"
path_abs = "0.4"
try_from = "0.3"
glob = "0.3"
walkdir = "2"
rayon = "1"
dirs = "1"
itertools = "0.8"
backoff = "0.1"
chrono = "0.4"
exitfailure = "0.5"
human-panic = "1"
atty = "0.2"
samuel = "0.1"
okra = { git = "https://github.com/jonathanmorley/okra", branch = "codegen" }
tokio-core = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
futures = "0.1"
clap-verbosity-flag = "0.2"
stderrlog = "0.4"
log-derive = "0.3"
recap = "0.1"
arn = "0.1"

[dependencies.reqwest]
version = "0.9"
features = ["trust-dns", "rustls"]

[target.'cfg(windows)'.dependencies]
rpassword = "3"

[dev-dependencies]
tempfile = "3"
assert_cmd = "0.11"
dirs = "1"
serial_test = "0.2"
serial_test_derive = "0.2"
predicates = "1"
